[cosmic-ray]
module-path = "src"
python-version = ""
timeout = 30.0
exclude-modules = ['src/ecdsa/_version.py', 'src/ecdsa/test*']
test-command = "pytest -x --fast src/"

[cosmic-ray.execution-engine]
name = "local"

[cosmic-ray.cloning]
method = "copy"
commands = []

[cosmic-ray.interceptors]
enabled = [ "spor", "pragma_no_mutate", "operators-filter",]

[cosmic-ray.operators-filter]
